### ISSUE TITLE
Images Not loading

### ISSUE THREAD

**Issue by makitstop** [FloricSpacer/AbyssDiver#127]
Not really anything else to mention, i'm not sure if it's an issue with how i downloaded the game or what, but none of the images or the sounds in the folder are loading when i open the game

**Comment by Ilyza91** [comment]
Are you playing it on your phone? Is so you should Joiplay. If not, did you unzip the folder? Else you can try to download it again and see if you can see the images if you open the folder.

**Comment by makitstop** [comment]
so, i just wanted to mention, while i am on my laptop, not my phone, it seems to have fixed itself in the night? so uh...thanks for the help i guess? also the game is very cool, i wish there were more CYOA games like it
