### ISSUE TITLE
Track "Reroll with Devil's Own" via variable

### ISSUE THREAD

**Issue by emmeken** [FloricSpacer/AbyssDiver#23]
"Reroll with Devil's Own" is tracked via `setup.devilsReroll`, but that means it will not be saved. This should be a variable instead.

The reason it's not a variable yet is that the "back" command is used to implement the reroll, which would also roll back the variable that tracks whether the reroll is already used up.

The solution would be to implement the reroll without using the "back" command and instead remove the curse/relic instead. That has to wait until #2 is complete.

**Comment by Ilyza91** [comment]
Solved it
