### ISSUE TITLE
Problems with the way we're using `noreturn`

### ISSUE THREAD

**Issue by emmeken** [FloricSpacer/AbyssDiver#24]
Currently all commerce balloon passages are tagged with `noreturn`, but the "Buy" passages are not. This means that if you actually buy an item, you'll go back to that passage when you're done balloon shopping. I thought the solution would be to tag the "Buy" passages with `noreturn` as well, but that's not correct: if you use any sidebar menu (stats, inventory etc.) and then click the "back" link there, you end up back on the layer where you used the balloon, not back in the balloon menu.

The companion conversations have the same issue, where you undo the conversation if you access one of the sidebar menus before the conversation is finished.

The root of this problem is that `noreturn` was designed for things like status menus, which are not part of the flow of the story, so the way you navigate through menus doesn't end up on the navigation stack. We shouldn't use `noreturn` on passages that are part of the story, since they will be cancelled whenever the menu is used.

A possible solution would be to look for the most recently visited hub passage (either by name or using a new tag) and link there from the balloon/conversation exit.

**Comment by Ilyza91** [comment]
Yeah I ran into the issue as well, with indeed the conversations. Going back to the latest hub passage seems like a better solution

**Comment by FloricSpacer** [comment]
Agreed, I think we should use a new method to return to hub passages.

**Comment by emmeken** [comment]
The navigation history has a limited number of items (currently set to 20), so if someone spends a lot of time shopping, it's possible they fill the entire history with shopping passages. So my initial idea of looking for the most recent hub passage in the history isn't going to work.

I think the idea of of the `noreturn` tag is actually fine: the problem is that the same variable (`$return`) is shared between the menu passages and location-independent story passages. Using a separate tag and a separate variable to store the return passage should solve it.

**Comment by emmeken** [comment]
On the other hand, that approach would require tagging every single passage that can be reached during a balloon event. It's probably easier to just store the previous passage at the first balloon passage. For the sidebar menu that doesn't work, because any menu option could be the first one, but for the commerce balloon there is only one initial passage.

**Comment by emmeken** [comment]
I think I found a practical solution: instead of explicitly tagging location-independent story passages, we check whether a passage has a `layerN` tag and save the last seen passage that did have such a tag.
