### ISSUE TITLE
ComfyUI resources

### ISSUE THREAD

**Issue by Nechochwen-D** [FloricSpacer/AbyssDiver#252]
Could you post a list of all the extensions and other resources you use for the sake of those of us who already have CUI set up?

**Comment by SPOOKEXE** [comment]
I had posted in the discord but i'll post it here for ya:

To use a custom instance of ComfyUI (for those that manually setup different version of ComfyUI with other support), simply run your custom comfyui instance, then run the proxy.py seperately using a command prompt or such.

You will need the following requirements as well: tqdm requests fastapi pydantic pillow websocket-client aiohttp uvicorn websockets (use pip install to install them)

Finally, make sure to have the ComfyUI-Inspyrenet-Rembg custom node installed by john-mnz 

Steps:
- Run comfyui
- Go to ComfyUI-Manager
- Custom Nodes Manager
- Install the ComfyUI-Inspyrenet-Rembg node
- Restart ComfyUI
- Open a new terminal
- Run pip install tqdm requests fastapi pydantic pillow websocket-client aiohttp uvicorn websockets
- Run python proxy.py in the local-gen folder

MODELS AND NODES:
- (Pony Checkpoint) https://civitai.com/models/376031/hassaku-xl-pony
- (Pony LORA) https://civitai.com/models/481529/dall-e-3-anime-style-pony
- (RemBG Node) https://github.com/john-mnz/ComfyUI-Inspyrenet-Rembg

**Comment by Nechochwen-D** [comment]
Thanks. Think you could add this to a readme in the script directory?

**Comment by SPOOKEXE** [comment]
Shall do

**Comment by SPOOKEXE** [comment]
https://github.com/FloricSpacer/AbyssDiver/pull/254
