### ISSUE TITLE
Acceptable curses for companions

### ISSUE THREAD

**Issue by FloricSpacer** [FloricSpacer/AbyssDiver#9]
One thing that someone brought up in the reddit thread is that companions may want to accept different curses if they have been swapped into a new body. For example, if a female PC swaps bodies with Khemia, then he'd happily take on a Sex Switcheroo curse that he'd normally be averse to. 

Currently we're using a constant for this, which means it won't change over the course of the game. And I think that makes sense for now. I suspect this might require a lot of work to solve for a relatively small benefit to players, so effort is better used elsewhere, but if either of you think there's an elegant solution to this problem then we can add it in. If not, then this should probably be lower priority than most of the other updates.

**Comment by Ilyza91** [comment]
I like this suggestion. If it's only sex switcheroo it can be fairly simple. for any character where the switch is true and the original stored gender is not the same as the mc stored original gender, they can be happy to take it. If we want to make it more complicated, let's say; also include gender reversal or for example some people not caring about switching back it will become more complicated. Let's keep it in the back of our minds while we finish what we are working on now.

**Comment by FloricSpacer** [comment]
I think it would optimally be more than just Sex Switcheroo, like a gender swapped companion would also be willing to take a gender reversal curse, and may not want an asset increasing curse that they wanted before (female Khemia probably wouldn't want bigger breasts, but wouldn't mind looking more masculine). So I think if it were more fully implemented it may be more complicated. Or maybe it could just be that there are 2 lists for each companion, 1 normal list and another if they are swapped with someone of the opposite sex?
